const sadhyaItems = [
  {
    name: "Upperi (Banana Chips)",
    img: "/bananachips.png",
    popupImg: "/bananachips.jpg",
    top: "42.5%",
    left: "26.8%",
    width: 90,
    ingredients: "Sliced banana, fried in coconut oil, salted",
    significance: "Crispy snack, served at start of Sadhya",
  },
  {
    name: "Sharkara Varatti",
    img: "/sharkara.png",
    popupImg: "/sharkara.jpg",
    top: "32%",
    left: "33.5%",
    ingredients: "Banana chips coated with jaggery (sharkara)",
    significance: "Sweet crunchy item, a traditional treat",
  },
  {
    name: "Pulli Inji",
    img: "/pulli.png",
    popupImg: "/pulli.jpg",
    top: "32%",
    left: "27%",
    width: 95,
    ingredients: "Ginger, jaggery, tamarind, spices",
    significance: "Sweet-sour ginger relish, aids digestion",
  },
  {
    name: "Salt",
    img: "/salt.png",
    popupImg: "/salt.jpg",
    top: "40%",
    left: "23%",
    width: 70,
    ingredients: "Plain rock/sea salt",
    significance: "Balances the flavors on the leaf",
  },
  {
    name: "Achar (Pickles)",
    img: "/achar.png",
    popupImg: "/achar.jpg",
    top: "46.5%",
    left: "22.5%",
    width: 100,
    ingredients: "Mango/lime pickles with spices",
    significance: "Adds tangy/spicy notes to the meal",
  },
  {
    name: "Pachadi (Beetroot)",
    img: "/pachadi.png",
    popupImg: "/pachadi.jpg",
    top: "29%",
    left: "38%",
    width: 100,
    ingredients: "Beetroot, curd, coconut, green chillies",
    significance: "Sweet-and-cool side, contrasts spicy items",
  },
  {
    name: "Pachadi (Pineapple)",
    img: "/ppachadi.png",
    popupImg: "/ppachadi.jpg",
    top: "29%",
    left: "44.7%",
    width: 100,
    ingredients: "Pineapple, curd, coconut, jaggery",
    significance: "Fruity sweet pachadi, palate cleanser",
  },
  {
    name: "Kichadi",
    img: "/kitchadi.png",
    popupImg: "/kitchadi.jpg",
    top: "30%",
    left: "51%",
    width: 110,
    ingredients: "Curd, cucumber/bitter gourd, coconut",
    significance: "Tangy curd-based side, similar to pachadi",
  },
  {
    name: "Olan",
    img: "/olan.png",
    popupImg: "/olan.jpg",
    top: "28.5%",
    left: "58%",
    width: 110,
    ingredients: "Ash gourd, coconut milk, cowpeas",
    significance: "Light, subtly seasoned curry",
  },
  {
    name: "Kalan",
    img: "/kallan.png",
    popupImg: "/kallan.jpg",
    top: "30%",
    left: "66%",
    width: 110,
    ingredients: "Yam (or raw banana), curd, coconut",
    significance: "Thick yogurt-based curry with texture",
  },
  {
    name: "Thoran",
    img: "/thoran.png",
    popupImg: "/thoran.jpg",
    top: "42.5%",
    left: "61%",
    width: 130,
    ingredients: "Shredded vegetable (cabbage/beans), coconut",
    significance: "Dry stir-fry, adds texture and crunch",
  },
  {
    name: "Chena Mezhukkupuratti",
    img: "/chena.png",
    popupImg: "/chena.jpg",
    top: "40.5%",
    left: "54.5%",
    width: 100,
    ingredients: "Fried/yet-stirred root vegetables (yam/chena)",
    significance: "Crispy, spiced vegetable preparation",
  },
  {
    name: "Mathan Erissery",
    img: "/mathan.png",
    popupImg: "/mathan.jpg",
    top: "43.5%",
    left: "47.3%",
    width: 90,
    ingredients: "Pumpkin, cowpeas, coconut, spices",
    significance: "Sweet-savory curry with pumpkin, balances the meal",
  },
  {
    name: "Kootu Curry",
    img: "/kuttucurry.png",
    popupImg: "/kuttucurry.jpg",
    top: "40.5%",
    left: "39%",
    width: 120,
    ingredients: "Black chickpeas, yam/plantain, coconut",
    significance: "Hearty curry to complement rice",
  },
  {
    name: "Aviyal",
    img: "/aviyal.png",
    popupImg: "/aviyal.jpg",
    top: "38.5%",
    left: "32.5%",
    width: 100,
    ingredients: "Mixed vegetables, coconut, yogurt",
    significance: "Signature mixed-vegetable dish of Sadhya",
  },
  {
    name: "Rice",
    img: "/choru.png",
    popupImg: "/rice.jpg",
    top: "70%",
    left: "40%",
    width: 250,
    ingredients: "Steamed rice",
    significance: "Main base for the curries",
  },
  {
    name: "Parippu Curry",
    img: "/parippu.png",
    popupImg: "/parippu.jpg",
    top: "60%",
    left: "62%",
    width: 80,
    ingredients: "Dal (lentils), ghee",
    significance: "First curry eaten with rice",
  },
  {
    name: "Sambar",
    img: "/sambar.png",
    popupImg: "/sambar.jpg",
    top: "63%",
    left: "65%",
    width: 90,
    ingredients: "Lentils, tamarind, vegetables, spices",
    significance: "Served after parippu",
  },
  {
    name: "Moru / Vellarikka Moru",
    img: "/vellamoru.png",
    popupImg: "/vellamoru.jpg",
    top: "60.5%",
    left: "68.5%",
    width: 100,
    ingredients: "Buttermilk, green chillies, curry leaves",
    significance: "Buttermilk curry — eaten after sambar",
  },
  {
    name: "Rasam",
    img: "/rasam.png",
    popupImg: "/rasam.jpg",
    top: "68%",
    left: "71.5%",
    width: 100,
    ingredients: "Tamarind, tomato, pepper, spices",
    significance: "Spicy-sour soup, helps with digestion",
  },
  {
    name: "Pappadam",
    img: "/pappadam.png",
    popupImg: "/pappadam.jpg",
    top: "65",
    left: "27.5%",
    width: 150,
    ingredients: "Crispy fried lentil wafers",
    significance: "Crunchy accompaniment to rice",
  },
  {
    name: "Banana (Pazham)",
    img: "/banana.png",
    popupImg: "/banana.jpg",
    top: "60%",
    left: "23.5%",
    width: 75,
    ingredients: "Ripe banana",
    significance: "Served toward the end of the meal",
  },
  {
    name: "Sharkara Payasam",
    img: "/brownpayasam.png",
    popupImg: "/brownpayasam.jpg",
    top: "40%",
    left: "71%",
    width: 90,
    ingredients: "Parippu or Sharkara payasam",
    significance: "Dessert to conclude the meal",
  },
  {
    name: "Palada Payasam",
    img: "/whitepayasam.png",
    popupImg: "/whitepayasam.jpg",
    top: "39.5%",
    left: "78%",
    width: 90,
    ingredients: "White/Semya or Palada payasam",
    significance: "Second dessert option",
  }
];
